# Use Amazon S3 to store uploaded files (see https://guides.rubyonrails.org/active_storage_overview.html#amazon-s3)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: your-region
#   bucket: your-bucket-name

# Use local file system to store uploaded files
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use Microsoft Azure Storage to store uploaded files (see https://guides.rubyonrails.org/active_storage_overview.html#microsoft-azure-storage)
# azure:
#   service: AzureStorage
#   storage_account_name: your-storage-account-name
#   storage_access_key: your-storage-access-key
#   container: your-container-name

# Use Google Cloud Storage to store uploaded files (see https://guides.rubyonrails.org/active_storage_overview.html#google-cloud-storage)
# google:
#   service: GCS
#   project: your-project-id
#   credentials: <%= Rails.root.join("path/to/gcsfile.json") %>
#   bucket: your-bucket-name

# Use Mirror Storage to store uploaded files on multiple services
# mirror:
#   service: Mirror
#   primary: local
#   mirrors:
#     - amazon
#     - azure 